version: "3.9"
services:
  mysqlserverbd2:
    container_name: mysqlserverbd2
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: banco
      MYSQL_PASSWORD: senha
      MYSQL_USER: usuario
      MYSQL_ROOT_PASSWORD: senharoot